#include <stdio.h>
#include "tryCatch.h"


void foo()
{
    raise(3);
}

int main (void)
{
    try {
        printf ("This code is inside the try statement.\n");
        foo();
    } catch {
        printf ("Error happened: %d\n", KISS_EXCEPTION);
    }
    printf("After.\n");
    return 0;
}